trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  artifactName: 'drop'

jobs:
  - job: Build
    displayName: 'Build and publish WAR'
    steps:
      - task: Gradle@3
        inputs:
          workingDirectory: 'spring-mvc-fiap'
          gradleWrapperFile: 'spring-mvc-fiap/gradlew'
          tasks: 'clean build'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'

      - task: CopyFiles@2
        inputs:
          contents: '**/build/libs/ROOT.war'
          targetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: '$(artifactName)'

  - job: Deploy
    displayName: 'Deploy to Azure App Service'
    dependsOn: Build
    steps:
      - download: current
      - script: ls -R $(Pipeline.Workspace)  # Opcional para debug
      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'AzureConnection'
          appName: 'spring-mvc-fiap-app'
          package: '$(Pipeline.Workspace)/**/ROOT.war'