trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  artifactName: 'drop'
  resourceGroup: 'spring-rg'
  webAppName: 'spring-mvc-fiap-app'
  planName: 'spring-plan'
  location: 'brazilsouth'

jobs:
  - job: Build
    displayName: 'Build and publish WAR'
    steps:
      - task: Gradle@3
        inputs:
          workingDirectory: 'spring-mvc-fiap'
          gradleWrapperFile: 'spring-mvc-fiap/gradlew'
          tasks: 'clean build'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'

      - task: CopyFiles@2
        inputs:
          contents: '**/build/libs/ROOT.war'
          targetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: '$(artifactName)'

  - job: Deploy
    displayName: 'Create infra and deploy to Azure App Service'
    dependsOn: Build
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'AzureConnection'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Criando grupo de recursos..."
            az group create --name $(resourceGroup) --location $(location)

            echo "Criando plano de serviço App Service (Linux)..."
            az appservice plan create \
              --name $(planName) \
              --resource-group $(resourceGroup) \
              --sku B1 \
              --is-linux

            echo "Criando Web App com runtime Java 21 + Tomcat..."
            az webapp create \
              --name $(webAppName) \
              --resource-group $(resourceGroup) \
              --plan $(planName) \
              --runtime "JAVA|21-java21"

      - download: current

      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'AzureConnection'
          appName: '$(webAppName)'
          package: '$(Pipeline.Workspace)/**/ROOT.war'
